Pages/AddCourt.cshtml.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using System.ComponentModel.DataAnnotations;
using Microsoft.AspNetCore.Authorization;
using MTLcourts.Data;
using MTLcourts.Models;
using Azure.Storage.Blobs.Models;
using Microsoft.WindowsAzure.Storage;
using Microsoft.WindowsAzure.Storage.Blob;
using Azure;

namespace MTLcourts.Pages

{

    //Only allows logged in users to access this page

     [Authorize]

    public class AddCourtModel : PageModel

    {

      

         private CourtsDbContext db;

         private readonly ILogger<RegisterModel> logger;



         private IWebHostEnvironment _environment;
         private readonly IConfiguration _configuration;



         public AddCourtModel(CourtsDbContext db, ILogger<RegisterModel> logger, IWebHostEnvironment environment, IConfiguration configuration ) {

            this.db = db;

            this.logger = logger;

             _environment = environment;

             _configuration = configuration;

        }



         [BindProperty]

        public Courts NewCourt { get; set; }



        [BindProperty]

        public IFormFile Upload { get; set; }

        [BindProperty]
        public List<BlobItem> BlobList { get; set; }

       
        


        public async Task<IActionResult> OnPostAsync()

        {

            if (ModelState.IsValid)

            {

              string photoUrl = null;

              if (Upload != null) {

              string _postedFileName = Upload.FileName;
              string _fileContentType = Upload.ContentType;
              string _actionMessage = " ";

              try
    {
        string blobstorageconnection = _configuration.GetSection("AzureStorage")["ConnectionString"];
        string containerName = _configuration.GetSection("AzureStorage")["ContainerName"];
            
        // get storage account obect using connection string    
        CloudStorageAccount cloudStorageAccount = CloudStorageAccount.Parse(blobstorageconnection);
        
        // create the blob client    
        CloudBlobClient blobClient = cloudStorageAccount.CreateCloudBlobClient();
        
        // get container reference.    
        CloudBlobContainer container = blobClient.GetContainerReference(containerName);
        
        // get the blob reference you want to work with    
        CloudBlockBlob blockBlob = container.GetBlockBlobReference(_postedFileName);
       
        //assuming we upload only image from here, else find dynamically 
        blockBlob.Properties.ContentType = _fileContentType; //"image/jpeg";
        
        using (var data = Upload.OpenReadStream())
        {
            await blockBlob.UploadFromStreamAsync(data);
        }

        _actionMessage = "Uploaded Successfully to Blob Storage";
    }
    catch (RequestFailedException ex)
    {
        _actionMessage = ex.ToString();
    }
                    
                // return  Page();

                //   string fileExtension = Path.GetExtension(Upload.FileName).ToLower();

                //   string[] allowedExtensions = { ".jpg", ".jpeg", ".gif", ".png" };

                //   if (!allowedExtensions.Contains(fileExtension)) 
                //   {

                //     // Display error and the form again

                //     ModelState.AddModelError(string.Empty, "Only image files (jpg, jpeg, gif, png) are allowed");

                //     return Page();

                //   }

                // var invalids = System.IO.Path.GetInvalidFileNameChars();

                // var newFileName = String.Join("_", Upload.FileName.Split(invalids, StringSplitOptions.RemoveEmptyEntries) ).TrimEnd('.');

                // var destPath = Path.Combine(_environment.ContentRootPath, "wwwroot", "Uploads", Upload.FileName);

                // try {

                // using (var fileStream = new FileStream(destPath, FileMode.Create))

                // {

                //     Upload.CopyTo(fileStream);

                // }

                // } catch (Exception ex) when (ex is IOException || ex is SystemException) {

                // // TODO: Log this as an error

                // ModelState.AddModelError(string.Empty, "Internal error saving the uploaded file");

                // return Page();

                // }

               
                photoUrl = Path.Combine("https://mtlcourtsblob.blob.core.windows.net/mtlcourtscontainer/", _postedFileName);
              }       
              var newCourt = new MTLcourts.Models.Courts {PhotoUrl = photoUrl, Name = NewCourt.Name, Address = NewCourt.Address, Description = NewCourt.Description, 
              PostalCode = NewCourt.PostalCode, AvgRating = NewCourt.AvgRating, CourtLatitude = NewCourt.CourtLatitude, CourtLongitude = NewCourt.CourtLongitude };

              db.Court.Add(newCourt);

              await db.SaveChangesAsync();

              return RedirectToPage("AddCourtSuccess");

            }else{
              return Page();
            }

        }

        public void OnGet()

        {

        }

    }

}

Pages/Court/AddCourt.cshtml.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using System.ComponentModel.DataAnnotations;
using Microsoft.AspNetCore.Authorization;
using MTLcourts.Data;
using MTLcourts.Models;
using Azure.Storage.Blobs.Models;
using Microsoft.WindowsAzure.Storage;
using Microsoft.WindowsAzure.Storage.Blob;
using Azure;

namespace MTLcourts.Pages

{

    //Only allows logged in users to access this page

     [Authorize(Roles = "Admin")]
    //  [Authorize(Roles = "Admin")]

    public class AddCourtModel : PageModel

    {

      

         private CourtsDbContext db;

         private readonly ILogger<RegisterModel> logger;



         private IWebHostEnvironment _environment;
         private readonly IConfiguration _configuration;

         public AddCourtModel(CourtsDbContext db, ILogger<RegisterModel> logger, 
         IWebHostEnvironment environment, IConfiguration configuration ) {

            this.db = db;

            this.logger = logger;

             _environment = environment;

             _configuration = configuration;

        }

        [BindProperty]
        public IFormFile Upload { get; set; }

        [BindProperty]
        public List<BlobItem> BlobList { get; set; }

        [BindProperty]
        public Courts NewCourt { get; set; }


       
        


        public async Task<IActionResult> OnPostAsync()

        {

            if (ModelState.IsValid)

            {

              string photoUrl = null;

              if (Upload != null) {

              string _postedFileName = Upload.FileName;
              string _fileContentType = Upload.ContentType;
              string _actionMessage = " ";

              try
    {
        string blobstorageconnection = _configuration.GetSection("AzureStorage")["ConnectionString"];
        string containerName = _configuration.GetSection("AzureStorage")["ContainerName"];
            
        // get storage account obect using connection string    
        CloudStorageAccount cloudStorageAccount = CloudStorageAccount.Parse(blobstorageconnection);
        
        // create the blob client    
        CloudBlobClient blobClient = cloudStorageAccount.CreateCloudBlobClient();
        
        // get container reference.    
        CloudBlobContainer container = blobClient.GetContainerReference(containerName);
        
        // get the blob reference you want to work with    
        CloudBlockBlob blockBlob = container.GetBlockBlobReference(_postedFileName);
       
        //assuming we upload only image from here, else find dynamically 
        blockBlob.Properties.ContentType = _fileContentType; //"image/jpeg";
        
        using (var data = Upload.OpenReadStream())
        {
            await blockBlob.UploadFromStreamAsync(data);
        }

        _actionMessage = "Uploaded Successfully to Blob Storage";
    }
    catch (RequestFailedException ex)
    {
        _actionMessage = ex.ToString();
    }
                    
                photoUrl = Path.Combine("https://mtlcourtsblob.blob.core.windows.net/mtlcourtscontainer/", _postedFileName);
              }       
              var newCourt = new MTLcourts.Models.Courts {PhotoUrl = photoUrl, Name = NewCourt.Name, Address = NewCourt.Address, Description = NewCourt.Description, 
              PostalCode = NewCourt.PostalCode, AvgRating = NewCourt.AvgRating, CourtLatitude = NewCourt.CourtLatitude, CourtLongitude = NewCourt.CourtLongitude };

              db.Court.Add(newCourt);

              await db.SaveChangesAsync();

              return RedirectToPage("AddCourtSuccess");

            }else{
              return Page();
            }

        }

        public void OnGet()

        {

        }

    }

}

Pages/Court/AddCourtSuccess.cshtml.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;

namespace MTLcourts.Pages
{
    public class AddCourtSuccessModel : PageModel
    {
        public void OnGet()
        {
        }
    }
}

Pages/Court/Delete.cshtml.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using MTLcourts.Models;
using MTLcourts.Data;
using Microsoft.EntityFrameworkCore;

namespace MTLcourts.Pages
{
    public class DeleteModel : PageModel
    {
        private readonly CourtsDbContext db;
        public DeleteModel(CourtsDbContext db) => this.db = db;

        [BindProperty(SupportsGet = true)]
        public int Id { get; set; }

        [BindProperty]
        public Courts Court { get; set; }


        public void OnGet()
        {
            Court = db.Court.Find(Id);
        }
        public async Task<IActionResult> OnPostAsync()
        {
            var CourtFromDB = await db.Court.FindAsync(Id);
            db.Court.Remove(CourtFromDB);
            await db.SaveChangesAsync();

            return RedirectToPage("DeleteSuccess");
        }
    }
}

Pages/Court/DeleteSuccess.cshtml.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;

namespace MTLcourts.Pages
{
    public class DeleteSuccessModel : PageModel
    {
        public void OnGet()
        {
        }
    }
}

Pages/Court/NewCourtSuccess.cshtml.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;

namespace MTLcourts.Pages
{
    public class NewCourtSuccessModel : PageModel
    {
        public void OnGet()
        {
        }
    }
}

Pages/Court/ViewCourt.cshtml.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using MTLcourts.Data;
using MTLcourts.Models;
using Microsoft.EntityFrameworkCore;
using System.Linq;
using System.ComponentModel.DataAnnotations;
using Microsoft.AspNetCore.Identity;

namespace MTLcourts.Pages
{
    public class ViewCourtModel : PageModel
    {
        private readonly ILogger<IndexModel> _logger;

        private readonly CourtsDbContext db;

        // private UserManager<IdentityUser> userManager;


        // UserManager<IdentityUser> userManager

        public ViewCourtModel(ILogger<IndexModel> logger, CourtsDbContext db)
        {
            _logger = logger;
            this.db = db;
            // this.userManager = userManager;
        }

        [BindProperty(SupportsGet = true)]
        public int Id { get; set; }

        public Courts court { get; set; }

        public Ratings rating { get; set; }

        public Comments comment { get; set; }

        [BindProperty]
        public Checkedin NewCheckIn { get; set; }

        // [BindProperty]
        // public IdentityUser currentuser { get; set; }


        

        public List<Comments> courtComments { get; set; }

        public List<Ratings> courtRating { get; set; }


        [BindProperty]
        [Required(ErrorMessage = "Review can not be empty")]
        public string Comment { get; set; }

        [BindProperty]
        [Required(ErrorMessage = "Set your rating to submit")]
        public int Rating { get; set; }

        [BindProperty]
        public double AvgRating { get; set; }

        // [BindProperty]
        //  public int PlayersCheckedIn { get; set; }

        [BindProperty]
        public bool IsCheckedIn { get; set; }

        [BindProperty]
         public int NumCheckedIn { get; set; }

        public int sum { get; set; }  =0 ;

        
    public List<Checkedin> checkinList { get; set; }

        public  void OnGet()
        {
            court =  db.Court.Include(court => court.User).Where(court => court.Id == Id).FirstOrDefault();
            // if (court == null) {
            //             // FIXME
            // }
            courtComments =  db.Comments.Include(comment => comment.User).Where(comment => comment.CourtsId == Id).ToList();

            checkinList = db.Checkedin.Where(i=>i.CourtsId==Id && i.IsCheckedIn==true).ToList();             
        foreach (var item in checkinList)
        {
            sum += item.NumCheckedIn;
        }


             var userName = User.Identity.Name;
            var user = db.Users.Where(u => u.UserName == userName).FirstOrDefault();
             var courtsId2 = Id;
           var newcheck =  db.Checkedin.Where(r => r.CourtsId == Id && r.User.UserName == userName).FirstOrDefault();
           
            if ( newcheck != null) {

                NewCheckIn = newcheck;
            }
            else{
            //     var userName2 = User.Identity.Name;
            // var user2 = db.Users.Where(u => u.UserName == userName2).FirstOrDefault();
            //  var courtsId2 = Id;
                
                var newCheckin = new MTLcourts.Models.Checkedin {User = user, CourtsId = courtsId2, Date = DateTime.Now, IsCheckedIn = false, 
              NumCheckedIn = 0 };
              NewCheckIn = newCheckin;
               db.Checkedin.Add(newCheckin);

              db.SaveChanges();
            
              RedirectToPage("ViewCourt", Id);
            }
           
            }

        public IActionResult OnPostCheckin()
        {

            var userName = User.Identity.Name;
            var user = db.Users.Where(u => u.UserName == userName).FirstOrDefault();
             var courtsId2 = Id;
             var newcheck =  db.Checkedin.Where(r => r.CourtsId == Id && r.User.UserName == userName).FirstOrDefault();
            //  checkin
            if(newcheck.IsCheckedIn){
                
                newcheck.IsCheckedIn= false;
              
            }
            // check out
            else {
                newcheck.NumCheckedIn= NumCheckedIn;
                newcheck.IsCheckedIn= true;
                newcheck.Date = DateTime.Now;

            }
            db.SaveChangesAsync();
            return RedirectToPage("ViewCourt", Id);
                 } 
           
        

        public IActionResult OnPostRating()
        {
            if (!ModelState.IsValid)
            {
                court = db.Court.Where(court => court.Id == Id).FirstOrDefault();
                courtComments = db.Comments.Include(comment => comment.User).Where(comment => comment.CourtsId == Id).ToList();
                // ModelState.AddModelError(string.Empty, "error");
//                return RedirectToPage("ViewCourt", Id);
                return Page();
            }
            // else
            // {
                var userName = User.Identity.Name;
                var user = db.Users.Where(u => u.UserName == userName).FirstOrDefault();
                var courtsId = Id;

                var newComment = new MTLcourts.Models.Comments
                {
                    CourtsId = courtsId,
                    User = user,
                    DateWhen = DateTime.Now,
                    Comment = Comment,
                };

                var newRating = new MTLcourts.Models.Ratings
                {
                    CourtsId = courtsId,
                    User = user,
                    Rating = Rating
                };


                rating = db.Ratings.Where(r => r.CourtsId == Id && r.User.UserName == userName).FirstOrDefault();
                var ratingsQuery = db.Ratings.Where(rating => rating.CourtsId == Id).ToList();
                var count = 0;
                var sum = 0;
                court = db.Court.Where(court => court.Id == Id).FirstOrDefault();
                if (rating != null)
                {
                    //ModelState.AddModelError(string.Empty, "You already rated this court. Review only is submitted.");
                    rating.Rating = Rating;
                    foreach (var rat in ratingsQuery)
                    {
                        sum += rat.Rating;
                        count++;
                    }
                    double AvgRatingNewUpdated = Math.Round((double)sum / (double)count, 2);
                    court.AvgRating = AvgRatingNewUpdated;

                    db.Comments.Add(newComment);
                    db.SaveChanges();
                    return RedirectToPage("ViewCourt", Id);
                }
                else
                {
                    foreach (var rat in ratingsQuery)
                    {
                        sum += rat.Rating;
                        count++;
                    }
                    double AvgRatingNew = Math.Round((double)(sum + Rating) / (double)(count + 1), 2);
                    court.AvgRating = AvgRatingNew;

                    db.Comments.Add(newComment);
                    db.Ratings.Add(newRating);
                    db.SaveChanges();

                    return RedirectToPage("ViewCourt", Id);
                }
            // }

            
        }
        
    }
}

Pages/Court/AddCourt.cshtml
@page
@model MTLcourts.Pages.AddCourtModel
@{
    ViewData["Title"] = "Add Court";
}

<h1 class="page-title">Create new court</h1>

    <div class="mt-3">
        <form method="post" enctype="multipart/form-data">
        <div asp-validation-summary="All" class="text-danger"></div>
            <div class="form-group row">
                <label asp-for="NewCourt.Name" class="col-sm-2 col-form-label">Name</label>
                <div class="col-sm-10">
                <input asp-for="NewCourt.Name" class="form-control"/>
                <span asp-validation-for="NewCourt.Name" class="text-danger"></span>
                </div>
            </div>
             <div class="form-group row">
                <label asp-for="NewCourt.Address" class="col-sm-2 col-form-label">Address</label>
                <div class="col-sm-10">
                <input asp-for="NewCourt.Address" class="form-control"/>
                <span asp-validation-for="NewCourt.Address" class="text-danger"></span>
                </div>
            </div>
             <div class="form-group row">
                <label asp-for="NewCourt.PostalCode" class="col-sm-2 col-form-label">Postal Code</label>
                <div class="col-sm-10">
                    <input asp-for="NewCourt.PostalCode" class="form-control"/>
                <span asp-validation-for="NewCourt.PostalCode" class="text-danger"></span>
                </div>
            </div>
            <div class="form-group row">
                <label asp-for="NewCourt.Description" class="col-sm-2 col-form-label">Description</label>
                <div class="col-sm-10">
                <textarea asp-for="NewCourt.Description" id = "myTextarea"  class="form-control" rows="5"></textarea>
                <span asp-validation-for="NewCourt.Description" class="text-danger"></span>
                </div>
            </div>

            <div class="form-group row">
                <label asp-for="NewCourt.CourtLatitude" class="col-sm-2 col-form-label">Latitude</label>
                <div class="col-sm-10">
                <input asp-for="NewCourt.CourtLatitude" class="form-control"/>
                <span asp-validation-for="NewCourt.CourtLatitude" class="text-danger"></span>
                </div>
            </div>

            <div class="form-group row">
                <label asp-for="NewCourt.CourtLongitude" class="col-sm-2 col-form-label">Longitude</label>
                <div class="col-sm-10">
                <input asp-for="NewCourt.CourtLongitude" class="form-control"/>
                <span asp-validation-for="NewCourt.CourtLongitude" class="text-danger"></span>
                </div>
            </div>




            @* <div class="form-group row">
                <label asp-for="NewCourt.PhotoUrl" class="col-sm-2 col-form-label">Photo Url - tp replace with upload</label>
                <div class="col-sm-10">
                <input asp-for="NewCourt.PhotoUrl"  class="form-control"/>
                <span asp-validation-for="NewCourt.PhotoUrl" class="text-danger"></span>
                </div>
            </div> *@

             <div class="form-group row">
                <label asp-for="Upload" class="col-sm-2 col-form-label">Image</label>
                <div class="col-sm-10">
                    <input asp-for="Upload"  class="form-control"/>
                <span asp-validation-for="Upload" class="text-danger"></span>
                </div>
            </div>
            <br>



            @* <div class="form-group row">
                <label asp-for="NewCourt.AvgRating" class="col-sm-2 col-form-label">Rating</label>
                <div class="form-check form-check-inline">
                <input asp-for="NewCourt.AvgRating" class="form-check-input" type="radio" name="inlineRadioOptions" id="inlineRadio1" value="1" checked>
                <label class="form-check-label" for="inlineRadio1">1</label>
                </div>
                <div class="form-check form-check-inline">
                <input  asp-for="NewCourt.AvgRating" class="form-check-input" type="radio" name="inlineRadioOptions" id="inlineRadio2" value="2">
                <label class="form-check-label" for="inlineRadio2">2</label>
                </div>
                <div class="form-check form-check-inline">
                <input  asp-for="NewCourt.AvgRating" class="form-check-input" type="radio" name="inlineRadioOptions" id="inlineRadio2" value="3">
                <label class="form-check-label" for="inlineRadio2">3</label>
                </div>
                <div class="form-check form-check-inline">
                <input  asp-for="NewCourt.AvgRating" class="form-check-input" type="radio" name="inlineRadioOptions" id="inlineRadio2" value="4">
                <label class="form-check-label" for="inlineRadio2">4</label>
                </div>
                <div class="form-check form-check-inline">
                <input  asp-for="NewCourt.AvgRating" class="form-check-input" type="radio" name="inlineRadioOptions" id="inlineRadio2" value="5">
                <label class="form-check-label" for="inlineRadio2">5</label>
                </div>
                 <span asp-validation-for="NewCourt.AvgRating" class="text-danger"></span>
              
            </div> *@

            
            <div class="form-group page-title">
                <button type="submit" class="btn btn-primary btn-info" >Add Court</button>
            </div>

        </form>
    </div> 

Pages/Court/AddCourtSuccess.cshtml
@page
@model MTLcourts.Pages.AddCourtSuccessModel
@{

    ViewData["Title"] = "";
}

@{
    <div class="login-reg-logout">
        <h1>Court Added</h1>
        <br>
        <a asp-area="" asp-page="/Index"> <button class="btn btn-primary btn-submit btn-info">Home Page</button> </a>
    </div>
            
    
}

Pages/Court/Delete.cshtml
@page "{id:int}"
@model MTLcourts.Pages.DeleteModel
@{
}

<div class="login-reg-logout">
     <h4>Court Record</h4>
     <p>Id: @Model.Court.Id</p>
     <p>Address: @Model.Court.Address</p>
     
     <br>
     <h5>Are you sure you want to delete this record?</h5>
     <br>
     <a asp-page="/Court/ViewCourt" asp-route-id="@Model.Court.Id" class="btn btn-info mr-4">Cancel</a>
     <br><br>
     <form method="POST">
          <input type="hidden" asp-for="Court.Id" />
          <input type="submit" value="Yes, Delete" class="btn btn-info" />
     </form>

</div>

Pages/Court/DeleteSuccess.cshtml
@page
@model MTLcourts.Pages.DeleteSuccessModel
@{
}

    
    <div class="login-reg-logout">
        <h1>Court Deleted</h1>
        <br>
        <a asp-area="" asp-page="/Index"> <button class="btn btn-primary btn-submit btn-info">Home Page</button> </a>
    </div>

Pages/Court/NewCourtSuccess.cshtml
@page
@model MTLcourts.Pages.NewCourtSuccessModel
@{
     ViewData["Title"] = "";
}

<h1>@ViewData["Title"]</h1>
@{

    <div class="login-reg-logout">
        <h1>New court created successfully</h1>
        <br>
        <a asp-area="" asp-page="/Index"> <button class="btn btn-primary btn-submit button-info">Home Page</button> </a>
    </div>
}

Pages/Court/ViewCourt.cshtml
@page "{Id:int}"
@* @page "{Id:int}/{handler?}" *@
@using System.Net
@model MTLcourts.Pages.ViewCourtModel
@inject SignInManager<IdentityUser> signInManager;

@{
    ViewData["Title"] = "View Court";
}

<div class="container viewCourtContainer">
    <div class="court-image-container">
        <div>
            <img class="img-responsive img-thumbnail" src="@Model.court.PhotoUrl" alt="basketball court photo">
        </div>
        <div class="court-info-container">
            <h2 class="court-name"><b>@Model.court.Name</b></h2>
            <p class="">@Model.court.Address</p>
            <h4 class="court-rating"><b>Rating:</b> @Model.court.AvgRating</h4>
            <p class="view-court-description">@Html.Raw(WebUtility.HtmlDecode(@Model.court.Description))</p>
             <h4 class="court-rating"><b>Checked In:</b> @Model.sum</h4>
        </div>
    </div>
    <br>


    @* <div>
        <form method="post" asp-page-handler="Checkin" asp-route-id="@Model.court.Id" >
        <div asp-validation-summary="All" class="text-danger"></div>
        @if (signInManager.IsSignedIn(User))
        {
        <div class="form-group row rating-container">
        <h4>Let others know you're on the court</h4>
        </div>
        <br><br>
        <div class="form-group row">
        <label asp-for="NewCheckIn.IsCheckedIn">Check In</label>
        <input type="checkbox" asp-for="NewCheckIn.IsCheckedIn" class="mr-5">
        <label for="Checkedin" asp-for="IsCheckedIn"> CheckedIn</label><br>
        <input type="checkbox" asp-for="IsCheckedIn" id="Checkedin" name="Checkedin" value="true" type="hidden">
        </div>
        <div class="form-group row">
        <label asp-for="NewCheckIn.NumCheckedIn" class="col-sm-2 col-form-label">Number if players checking in</label>
        <div class="col-sm-10">
        <input asp-for="NewCheckIn.NumCheckedIn" class="form-control"/>
        <span asp-validation-for="NewCheckIn.NumCheckedIn" class="text-danger"></span>
        </div>
        </div>
        <div class="form-group">
        <button type="submit" class="btn btn-primary btn-submit button-submit">Check In</button>
        </div>
        }
        </form>
        </div> *@


    <div class="comments-rating">
        <form asp-page-handler="checkin" method="post" enctype="multipart/form-data">
            <div asp-validation-summary="All" class="text-danger"></div>
            @if (signInManager.IsSignedIn(User))
            {
                
                 @if (@Model.NewCheckIn.IsCheckedIn)
                {
                     <h4>Don't forget to say Goodbye!</h4>
                    <div class="form-group checkin-form">
                        <button type="submit" class="btn btn-primary btn-submit button-submit" asp-page-handler="Checkin">Check
                            Out</button>
                    </div>
                }
                else
                {
                    <h4>Let others know you're on the court</h4>
                   
                    <div class="checkin-form">
                        <label class=""> Number of players with you</label>
                        <input asp-for="NumCheckedIn" class="numOfPlayers" min="1" max="20" value="1" />
                       
                        <button type="submit" class="btn btn-primary btn-submit button-submit" asp-page-handler="Checkin">Check
                            In</button>
                    </div>

                }
            }
        </form>
                    <br>

                
                <hr> 
                

             <div class="comments-rating">
        <form asp-page-handler="rating" method="post" enctype="multipart/form-data" >
            <div asp-validation-summary="All" class="text-danger"></div>
            @if (signInManager.IsSignedIn(User))
            {    
                <div class="form-group row rating-container">
                    <h4>Your Rating</h4>
                    &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
                    <span class="star-rating">
                        <input class="form-radio-input" value="1" type="radio" asp-for="Rating" /><i></i>
                        <input class="form-radio-input" value="2" type="radio" asp-for="Rating" /><i></i>
                        <input class="form-radio-input" value="3" type="radio" asp-for="Rating" /><i></i>
                        <input class="form-radio-input" value="4" type="radio" asp-for="Rating" /><i></i>
                        <input class="form-radio-input" value="5" type="radio" asp-for="Rating" /><i></i>
                    </span>
                    <span asp-validation-for="Rating" class=text-danger></span>
                </div>
                <br><br>
                <div class="form-group row">
                    <h4>Your Review</h4>
                    <div class="col review-text-container">
                        <textarea asp-for="Comment" class="form-control your-review-textarea"></textarea>
                        <span asp-validation-for="Comment" class="text-danger"></span>
                    </div>
                </div>
                <br>
                <div class="form-group">
                    <button type="submit" class="btn btn-primary btn-submit button-submit">Submit</button>
                </div>
                @* <div class="form-group row">
                    <label for="Checkedin" asp-for="Checkedin.IsCheckedIn"> CheckedIn</label><br>
                    <input type="checkbox" asp-for="Checkedin.IsCheckedIn" id="Checkedin" name="Checkedin" value="CheckedIn">

                    </div> *@
            }
        </form>
    </div>
    <br><br>
    <div class="court-reviews-container">
        <hr>
        <h2>Court Reviews</h2>
        <hr>
        <div class="player-reviews">
            @foreach (var courtComments in Model.courtComments)
            {
                <div class="row">
                    <div class="col-3">
                        <h6>@courtComments.User</h6>
                        <p><i>@courtComments.DateWhen.ToString($"{0:dd/MM/yyyy}")</i></p>
                    </div>
                    <div class="col">
                        <p>@courtComments.Comment</p>
                    </div>
                </div>
                <hr>
            }
        </div>
    </div>
    <br>
    @if (signInManager.IsSignedIn(User) && User.IsInRole("Admin"))
    {
        <div class="del-edit-btn-container">
            <a asp-page="/Court/delete" asp-route-id="@Model.court.Id" class="btn btn-info">Delete Court</a>
            <a class="btn btn-info" asp-page="/Court/CourtEdit" asp-route-id="@Model.court.Id">Edit Court</a>
        </div>
    }
</div>